---
- name: Create folder
  shell: mkdir -p {{ ftp_home }}

- name: Create Apache vhost in conf.d folder
  template: src=vhost.conf.j2 dest={{ apache_dir }}/{{ site_url }}.conf owner=root

- name: Enable the vhost on Debian family
  shell: a2ensite {{ site_url }}.conf
  when: ansible_os_family == "Debian"

- name: Reload apache
  service: name={{ apache }} state=reloaded 
